# Playbook to install and configure microk8s
---
- name: "Install microk8s and configure"
  hosts: "microk8s"
  become: true
  tasks:
    - name: "Snap install"
      community.general.snap:
        classic: true
        name:
          - "microk8s"

    - name: "Apt install"
      ansible.builtin.apt:
        name: "python3-kubernetes"
        state: "present"

    - name: "Adding user to microk8s group"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "microk8s"
        append: true

    - name: "Reset Connection"
      ansible.builtin.meta: "reset_connection"

    - name: "Change kube folder ownership"
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"
        state: "directory"

    - name: "Add alias for foo user"
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "alias kubectl='microk8s kubectl'"
        owner: "{{ ansible_user }}"
        mode: "0644"
        state: "present"
        insertafter: "EOF"
        create: true

    - name: "Enable microk8s common modules"
      ansible.builtin.command: "microk8s enable dns hostpath-storage dashboard helm3"
      register: myoutput
      changed_when: true

- name: "Create Dashboard Service Manifest"
  hosts: "microk8s"
  tasks:
    - name: "Deploy Dashboard Service"
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ microk8s_config_path }}"
        definition:
          apiVersion: "v1"
          kind: "Service"
          metadata:
            name: "k8s-dash"
            namespace: "kube-system"
          spec:
            selector:
              k8s-app: "kubernetes-dashboard"
            type: "NodePort"
            ports:
              - name: "https"
                nodePort: 30443
                port: 443
                targetPort: 8443
                protocol: "TCP"

    - name: "Enable microk8s common modules"
      ansible.builtin.command: "/snap/bin/microk8s kubectl create token default"
      register: "microk8s_token"
      changed_when: true

    - name: "Display microk8s url and token"
      ansible.builtin.debug:
        msg: |
          "MicroK8S Dashboard URL: https://{{ ansible_host }}:30443/#/login"
          "Dashboard Token: {{ microk8s_token.stdout }}"
