# Playbook to create k8s namespace, deploy nginx pod, and configure loadbalancer service
---
- name: "Create K8S namespace and deploy nginx"
  hosts: "microk8s"
  tasks:
    - name: "Create a k8s namespace"
      kubernetes.core.k8s:
        name: "nginx-test"
        api_version: "v1"
        kind: "Namespace"
        state: "present"
        kubeconfig: "{{ microk8s_config_path }}"

    - name: "Deploy NGINX container"
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ microk8s_config_path }}"
        definition:
          apiVersion: "v1"
          kind: "Deployment"
          metadata:
            name: "nginx-test"
            namespace: "nginx-test"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "nginx-test"
            template:
              metadata:
                labels:
                  app: "nginx-test"
              spec:
                containers:
                  - name: "nginx"
                    image: "nginx:latest"
                    ports:
                      - containerPort: 80

    - name: "Deploy NGINX LoadBalancer service"
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ microk8s_config_path }}"
        definition:
          apiVersion: "v1"
          kind: "Service"
          metadata:
            name: "nginx-loadbalancer-service"
            namespace: "nginx-test"
          spec:
            type: "LoadBalancer"
            externalIPs:
              - "{{ ansible_host }}"
            ports:
              - name: "http"
                port: 8080
                targetPort: 80
            selector:
              app: "nginx-test"
