# Playbook to test connection to inventory with ping module
---
- name: "Ping Test"
  hosts: "microk8s"
  gather_facts: false # Optional: Disable fact gathering to speed up testing
  tasks:
    - name: "Test connection to host"
      ansible.builtin.ping:
      register: "ping_result"

    - name: "Debug ping result"
      ansible.builtin.debug:
        msg: "{{ ping_result }}"
